# Generated by Django 3.1.2 on 2020-11-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_remove_table_orders'),
        ('orders', '0002_auto_20201114_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
