# Generated by Django 3.1.2 on 2020-11-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_remove_table_orders'),
        ('orders', '0003_auto_20201118_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
