# Generated by Django 3.1.2 on 2020-11-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201119_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
