# Generated by Django 3.1.2 on 2020-10-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='currentorder',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='joinWith',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
