# Generated by Django 3.1.2 on 2020-10-31 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20201031_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='join_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='_table_join_with_+', to='tables.Table'),
        ),
    ]
