# Generated by Django 3.1.2 on 2020-11-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('tables', '0003_auto_20201031_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='join_with',
            field=models.ManyToManyField(blank=True, related_name='_table_join_with_+', to='tables.Table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='orders',
            field=models.ManyToManyField(through='orders.Order', to='products.Product'),
        ),
    ]
