# Generated by Django 3.1.2 on 2020-11-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20201102_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='join_with',
        ),
        migrations.AddField(
            model_name='table',
            name='join_with',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table'),
        ),
    ]
