# Generated by Django 3.1.2 on 2020-11-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20201105_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='Nueva mesa', max_length=200),
        ),
    ]
