# Generated by Django 3.1.2 on 2020-11-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20201105_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='mesa 1', max_length=200),
            preserve_default=False,
        ),
    ]
