# Generated by Django 3.1.2 on 2020-11-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='orders',
        ),
    ]
