# Generated by Django 3.1.2 on 2020-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_remove_table_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='join_direction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
